---
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

# Overrides
Layout/LineLength:
  Max: 120

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
