name: "CI"
on: push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.7", "3.0", "3.1", "3.2"]
        gemfile:
          - circuitbox_1
          - circuitbox_2
        exclude:
          - ruby: "3.2"
            gemfile: "circuitbox_1"
          - ruby: "3.1"
            gemfile: "circuitbox_1"
          - ruby: "3.0"
            gemfile: "circuitbox_1"
          - ruby: "2.5"
            gemfile: "circuitbox_2"

    runs-on: ubuntu-22.04
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 3
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake test
